
{% set data = load_setup_py_data() %}

package:
  name: conda-diff
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    {% for ep in data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}


requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - conda_diff
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: https://github.com/k-dominik/conda-diff
  license: MIT
  summary: Command line tool to compare conda environments
